insert into product(name, type, category, link,icon,content) values('링고비즈', 'food','communication',  '../../enterprise.kt.com/pd/P_PD_CC_TE_005.do.html','ringobiz.png','365일 내 매장을 저렴하게 홍보하는 특별한 통화연결음 (전화안내멘트)');
insert into product(name, type, category, link,icon,content) values('발신정보알리미', 'food','communication', '../../enterprise.kt.com/pd/P_PD_CC_TE_006.do.html','barsinJungbo.png','우리 회사/매장의 상호명을 표시해주는 서비스');
insert into product(name, type, category, link,icon,content) values('위치문자', 'food','communication', '../../enterprise.kt.com/pd/P_PD_CC_CM_007.do.html','gpsmessage.png','"고객 위치"기반의 타겟 마케팅 서비스를 제공합니다.');
insert into product(name, type, category, link,icon,content) values('가게정보알림메시지 (소상공인형)', 'food','communication', '../../enterprise.kt.com/pd/P_PD_CC_CM_005.do.html','store_info_message.png','걸려온 전화가 끝나면 알아서 홍보문자를 보내주는 우리가게 도우미');
insert into product(name, type, category, link,icon,content) values('콜체크인', 'food','communication', '../../enterprise.kt.com/pd/P_PD_CC_IN_005.do.html','callcheckin.png','전화 한 통으로 간편하게 출입등록을 할 수 있는 코로나 방역 특화 서비스');
insert into product(name, type, category, link,icon,content) values('안심번호 0502', 'food','communication','../../enterprise.kt.com/pd/P_PD_CC_IN_004.do.html','safenumber.png','이용자의 개인정보를 지켜주는 가상번호 서비스');
insert into product(name, type, category, link,icon,content) values('전국대표번호', 'food','communication','../../enterprise.kt.com/pd/P_PD_CC_IN_001.do.html','daponumber.png','전국 대리점 번호가 하나의 대표번호로 통합되는 서비스');

insert into product(name, type, category, link,icon,content) values('AI 방역로봇', 'food','smart','../../enterprise.kt.com/pd/P_PD_AI_RB_005.do.html','airCleanerAI.png','감염의 위험과 함께하는 엔데믹의 시대에 일상의 안전을 지키는 AI 로봇 기반의 새로운 방역 패러다임');
insert into product(name, type, category, link,icon,content) values('AI 서비스로봇', 'food','smart','../../enterprise.kt.com/pd/P_PD_AI_RB_004.do.html','servingAI.png','바쁜 일터를 돕고, 매장의 경쟁력을 높여주는 로봇 솔루션');
insert into product(name, type, category, link,icon,content) values('AI 뉴바리스타 로봇', 'food','smart','../../enterprise.kt.com/pd/P_PD_AI_RB_002.do.html','baristaAI.png','KT AI와 Robotics 기술이 만나 완전 무인카페 서비스를 제공하는 뉴바리스타 로봇');

insert into product(name, type, category, link,icon,content) values('상권분석솔루션', 'food','marketing','../../enterprise.kt.com/pd/P_PD_AI_BD_002.do.html','sanggunbunsuck_solution.png','전국 상업용 건물 및 사업체 정보를 기반으로 매장 매출 분석 및 출점 후보지 분석을 지원하는 상권분석 솔루션');
insert into product(name, type, category, link,icon,content) values('타겟마케팅', 'food','marketing','../../enterprise.kt.com/pd/P_PD_AI_BD_004.do.html','target_marketing.png','고객의 이용패턴을 분석하여, 최적의 고객군에게 차별화된 서비스를 제공하는 타겟 마케팅 서비스');
insert into product(name, type, category, link,icon,content) values('잘나가게', 'food','marketing','../../enterprise.kt.com/pd/P_PD_AI_BD_006.do.html','jalnagagae.png','유용한 상권 정보와 영업 TIP을 보내주는 예비창업자/소상공인 대상 문자 알림 서비스');